/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;



public class MainFrame extends javax.swing.JFrame {

    DefaultTableModel modelMahasiswa;
    boolean isEdit;

    
    public MainFrame() {
        initComponents();
        // Tambahkan kolom baru
        String[] kolom = {"ID", "NIM", "Nama", "Tahun Masuk"};
        modelMahasiswa = new DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(modelMahasiswa);

        isEdit = false;
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblNim1 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        lblTahunMasuk = new javax.swing.JLabel();
        txtTahunMasuk = new javax.swing.JTextField();
        UploadCsv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        btnSubmit.setText("Tambah");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblNama.setText("Nama");

        tblMahasiswa.setBackground(new java.awt.Color(255, 204, 255));
        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblNim1.setText("NIM");

        lblTahunMasuk.setText("Tahun Masuk");

        txtTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunMasukActionPerformed(evt);
            }
        });

        UploadCsv.setText("Upload CSV");
        UploadCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadCsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNim1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UploadCsv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim1)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahunMasuk)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(UploadCsv))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        insert(); 

        txtNama.setText("");
        txtNim.setText("");
        txtTahunMasuk.setText("");

        loadData(); 

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
            return; 
        }
        int id = (int) tblMahasiswa.getValueAt(row, 0); 

        try {
            Connection conn = DbConnection.connect();
            String sql = "DELETE FROM mahasiswa WHERE id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);
            ps.executeUpdate();
            conn.close();

            loadData(); 
            System.out.println("Data berhasil dihapus!");

        } catch (Exception e) {
            System.out.println("Delete error: " + e.getMessage());
        }


    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
                                     
   int row = tblMahasiswa.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!");
        return;
    }

    // --- PASTIKAN MAPPING KOLM BENAR ---
    // modelMahasiswa: 0=id, 1=nim, 2=nama, 3=tahunmasuk

    // Jika textfield kosong -> isi dulu dari tabel (fase edit)
    if (txtNama.getText().trim().isEmpty() && txtNim.getText().trim().isEmpty() && txtTahunMasuk.getText().trim().isEmpty()) {

        // Ambil dari kolom yang sesuai
        Object nimObj = tblMahasiswa.getValueAt(row, 1);
        Object namaObj = tblMahasiswa.getValueAt(row, 2);
        Object tahunObj = tblMahasiswa.getValueAt(row, 3);

        txtNim.setText(nimObj == null ? "" : nimObj.toString());
        txtNama.setText(namaObj == null ? "" : namaObj.toString());
        txtTahunMasuk.setText(tahunObj == null ? "" : tahunObj.toString());

        JOptionPane.showMessageDialog(this, "Silakan ubah data di textfield, lalu klik Edit lagi untuk menyimpan.");
        return;
    }

    // Jika field sudah terisi -> simpan perubahan (fase simpan)
    String nim = txtNim.getText().trim();
    String nama = txtNama.getText().trim();
    String tahunText = txtTahunMasuk.getText().trim();

    if (nim.isEmpty() || nama.isEmpty() || tahunText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi sebelum menyimpan.");
        return;
    }

    int tahun;
    try {
        tahun = Integer.parseInt(tahunText);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Tahun masuk harus berupa angka.");
        return;
    }

    try {
        int id = (int) tblMahasiswa.getValueAt(row, 0);

        Connection conn = DbConnection.connect();
        String sql = "UPDATE mahasiswa SET nim = ?, nama = ?, tahunmasuk = ? WHERE id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, nim);
        ps.setString(2, nama);
        ps.setInt(3, tahun);
        ps.setInt(4, id);

        ps.executeUpdate();
        ps.close();
        conn.close();

        // refresh tabel dari DB
        loadData();

        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

        // Bersihkan textfield setelah update
        txtNama.setText("");
        txtNim.setText("");
        txtTahunMasuk.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Edit error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunMasukActionPerformed

    private void UploadCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadCsvActionPerformed
                                                 
    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    int result = fc.showOpenDialog(this);

    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        String file = fc.getSelectedFile().getAbsolutePath();
        importCsv(file);
    }

    }//GEN-LAST:event_UploadCsvActionPerformed

    private void insert() {
    try {
        Connection conn = DbConnection.connect();

        if (conn == null) {
            System.out.println("Koneksi gagal!");
            return;
        }

        String sql = "INSERT INTO mahasiswa (nim, nama, tahunmasuk) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, txtNim.getText());
        ps.setString(2, txtNama.getText());
        ps.setInt(3, Integer.parseInt(txtTahunMasuk.getText()));

        ps.executeUpdate();
        conn.close();

        loadData();
        System.out.println("✅ Data berhasil disimpan ke database!");

    } catch (Exception e) {
        System.out.println("Insert error: " + e.getMessage());
    }

    }

    private void importCsv(String filePath) {
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {

        String line;
        boolean skipHeader = true;

        Connection conn = DbConnection.connect();
        String sql = "INSERT INTO mahasiswa (nim, nama, tahunmasuk) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        while ((line = br.readLine()) != null) {
            if (skipHeader) { 
                skipHeader = false; 
                continue; 
            }

            String[] data = line.split(",");

            if (data.length < 3) continue; // validasi

            String nim = data[0].trim();
            String nama = data[1].trim();
            int tahun = Integer.parseInt(data[2].trim());

            // INSERT ke database
            ps.setString(1, nim);
            ps.setString(2, nama);
            ps.setInt(3, tahun);
            ps.executeUpdate();
        }

        conn.close();
        loadData(); // Refresh JTable

        javax.swing.JOptionPane.showMessageDialog(this,
            "Berhasil mengimpor data dari CSV!");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error membaca CSV: " + e.getMessage());
    }
}


 
    
   private void loadData() {

    try {
        Connection conn = DbConnection.connect();
        Statement st = conn.createStatement();

        // --- CEK APAKAH TABEL KOSONG ---
        ResultSet rsCount = st.executeQuery("SELECT COUNT(*) FROM mahasiswa");
        rsCount.next();
        int count = rsCount.getInt(1);

        if (count == 0) {
            // Dapatkan nama SEQUENCE untuk kolom ID
            ResultSet rsSeq = st.executeQuery(
                "SELECT pg_get_serial_sequence('mahasiswa', 'id')"
            );
            rsSeq.next();
            String seqName = rsSeq.getString(1);

            // Reset sequence agar ID mulai dari 1
            st.executeUpdate("ALTER SEQUENCE " + seqName + " RESTART WITH 1");
        }

        // --- LOAD DATA TABEL ---
        ResultSet rs = st.executeQuery("SELECT * FROM mahasiswa ORDER BY id ASC");

        modelMahasiswa.setRowCount(0);
        while (rs.next()) {
            Object[] row = {
                rs.getInt("id"),
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getInt("tahunmasuk")
            };
            modelMahasiswa.addRow(row);
        }

        conn.close();
    } catch (Exception e) {
        System.out.println("Load data error: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UploadCsv;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim1;
    private javax.swing.JLabel lblTahunMasuk;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTahunMasuk;
    // End of variables declaration//GEN-END:variables

}
